create table if not exists modelos (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

alter table modelos enable row level security;

insert into modelos (nome) values
  ('Redondo 60x60'),
  ('Gota 54x60'),
  ('Redondo 40x40'),
  ('Orgânica 90x50')
on conflict (nome) do nothing;

drop policy if exists "autenticados leem modelos" on modelos;
create policy "autenticados leem modelos"
on modelos for select to authenticated using (true);

drop policy if exists "admin cria modelos" on modelos;
create policy "admin cria modelos"
on modelos for insert to authenticated
with check (
  exists (
    select 1 from perfis p
    where p.usuario_id = auth.uid() and p.papel = 'admin'
  )
);

drop policy if exists "admin atualiza modelos" on modelos;
create policy "admin atualiza modelos"
on modelos for update to authenticated
using (
  exists (
    select 1 from perfis p
    where p.usuario_id = auth.uid() and p.papel = 'admin'
  )
)
with check (
  exists (
    select 1 from perfis p
    where p.usuario_id = auth.uid() and p.papel = 'admin'
  )
);

create index if not exists modelos_ativo_nome_idx on modelos(ativo, nome);
