import { supabase } from './supabase';

const SETORES={1:'Corte e destaque',2:'Cola e EVA',3:'Colagem do couro',4:'Limpeza',5:'Finalização e alça',6:'Embalagem'};
const PAGE=1000;
let cache={avarias:[],bipagens:[],perfis:[]};

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmt(v){return new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function inicioPeriodo(tipo){const d=new Date();d.setHours(0,0,0,0);if(tipo==='7d')d.setDate(d.getDate()-6);else if(tipo==='30d')d.setDate(d.getDate()-29);else if(tipo==='mes')d.setDate(1);return d}
async function todas(tabela,select,desde){const out=[];for(let from=0;;from+=PAGE){let q=supabase.from(tabela).select(select).gte('criado_em',desde.toISOString()).order('criado_em',{ascending:false}).range(from,from+PAGE-1);const{data,error}=await q;if(error)throw error;const lote=data||[];out.push(...lote);if(lote.length<PAGE)break;}return out}

function estilos(){if(document.getElementById('rp-style'))return;const s=document.createElement('style');s.id='rp-style';s.textContent=`
.rpNav{display:flex!important;align-items:center;gap:7px;white-space:nowrap}.rpOverlay{position:fixed;inset:0;z-index:99999;background:#eef3f9;padding:18px;overflow:auto;font-family:Inter,Arial,sans-serif;color:#172033}.rpShell{max-width:1500px;margin:auto;display:grid;gap:14px}.rpTop,.rpPanel{background:#fff;border:1px solid #dfe7f1;border-radius:18px;box-shadow:0 5px 18px #0f172a0a}.rpTop{padding:18px 22px;display:flex;justify-content:space-between;gap:14px;align-items:center}.rpTop h1{margin:2px 0;font-size:clamp(25px,2.2vw,38px)}.rpTop p{margin:0;color:#64748b}.rpTop small{color:#dc2626;font-weight:900;letter-spacing:1px}.rpBack{width:auto!important;margin:0!important;background:#172033!important;padding:10px 15px!important}.rpPanel{padding:18px}.rpQuick{display:flex;gap:8px;flex-wrap:wrap}.rpQuick button{width:auto;margin:0;padding:9px 13px;background:#e2e8f0;color:#475569}.rpQuick button.active{background:#2563eb;color:#fff}.rpCards{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.rpCard{background:#f8fafc;border:1px solid #e5ebf3;border-radius:14px;padding:14px}.rpCard span{display:block;color:#64748b;font-size:12px;font-weight:800}.rpCard strong{display:block;font-size:28px;margin-top:4px}.rpGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.rpTitle{margin:0 0 4px}.rpSub{color:#64748b;font-size:13px;margin-bottom:12px}.rpRow{display:grid;grid-template-columns:1fr auto;gap:10px;padding:10px 0;border-bottom:1px solid #edf2f7;align-items:center}.rpRow:last-child{border-bottom:0}.rpRow small{display:block;color:#64748b}.rpDetail{display:grid;grid-template-columns:1fr 1fr 1fr .8fr 130px auto;gap:9px;align-items:center;padding:10px 6px;border-bottom:1px solid #edf2f7;font-size:13px}.rpBadge{display:inline-flex;width:max-content;border-radius:999px;padding:5px 8px;font-size:11px;font-weight:900}.rpBadge.q{background:#fee2e2;color:#991b1b}.rpBadge.a{background:#fef3c7;color:#92400e}.rpBadge.r{background:#dcfce7;color:#166534}.rpAction{width:auto!important;margin:0!important;padding:7px 9px!important;background:#0f766e!important;font-size:11px!important}.rpEmpty{text-align:center;padding:25px;color:#94a3b8}.rpStatus{padding:10px;border-radius:10px;background:#eff6ff;color:#1d4ed8;font-weight:800;margin-top:10px}
@media(max-width:1000px){.rpCards{grid-template-columns:repeat(2,1fr)}.rpGrid{grid-template-columns:1fr}.rpDetail{grid-template-columns:1fr 1fr}.rpDetail time,.rpDetail button{grid-column:auto}}@media(max-width:560px){.rpOverlay{padding:9px}.rpTop{align-items:flex-start;flex-direction:column}.rpBack{width:100%!important}.rpCards{grid-template-columns:1fr}.rpDetail{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

function nomePessoa(id){return cache.perfis.find(p=>p.usuario_id===id)?.nome||'Usuário'}
function agrupar(lista,chave,label){const m=new Map();for(const r of lista){const k=chave(r);m.set(k,(m.get(k)||0)+1)}return[...m.entries()].sort((a,b)=>b[1]-a[1]).map(([k,v])=>({nome:label(k),total:v}))}

async function carregar(periodo){const desde=inicioPeriodo(periodo);const [av,bip,{data:perfis,error:ep}]=await Promise.all([
 todas('avarias','id,produto_id,setor_id,usuario_id,tipo,motivo,observacao,status,reprocessado_em,reprocessado_por,criado_em,produtos(codigo_barras,modelo)',desde),
 todas('bipagens','id,produto_id,setor_id,criado_em',desde),
 supabase.from('perfis').select('usuario_id,nome,setor_id,ativo')
]);if(ep)throw ep;cache={avarias:av,bipagens:bip,perfis:perfis||[]};render(periodo)}

function render(periodo){const o=document.querySelector('.rpOverlay');if(!o)return;const av=cache.avarias;const quebradas=av.filter(x=>x.tipo==='Quebrada').length,avariadas=av.filter(x=>x.tipo==='Avariada').length,reprocessadas=av.filter(x=>x.status==='Reprocessada').length;const iniciadas=new Set(cache.bipagens.filter(x=>Number(x.setor_id)===1).map(x=>x.produto_id)).size;const perdasAbertas=new Set(av.filter(x=>x.status!=='Reprocessada').map(x=>x.produto_id)).size;const taxa=iniciadas?((perdasAbertas/iniciadas)*100):0;const aproveitamento=Math.max(0,iniciadas-perdasAbertas);
 o.querySelector('[data-rp-quebradas]').textContent=quebradas;o.querySelector('[data-rp-avariadas]').textContent=avariadas;o.querySelector('[data-rp-reprocessadas]').textContent=reprocessadas;o.querySelector('[data-rp-aproveit]').textContent=aproveitamento;o.querySelector('[data-rp-taxa]').textContent=`${taxa.toFixed(1)}%`;
 const setores=agrupar(av,r=>Number(r.setor_id),k=>SETORES[k]||'-');const modelos=agrupar(av,r=>r.produtos?.modelo||'-',k=>k);const pessoas=agrupar(av,r=>r.usuario_id,k=>nomePessoa(k));
 const preencher=(sel,dados)=>{const el=o.querySelector(sel);el.innerHTML=dados.length?dados.map(x=>`<div class="rpRow"><div><b>${esc(x.nome)}</b><small>ocorrências</small></div><strong>${x.total}</strong></div>`).join(''):'<div class="rpEmpty">Sem ocorrências.</div>'};preencher('[data-rp-setores]',setores);preencher('[data-rp-modelos]',modelos);preencher('[data-rp-pessoas]',pessoas);
 const det=o.querySelector('[data-rp-detalhes]');det.innerHTML=av.length?av.slice(0,300).map(r=>`<div class="rpDetail"><div><b>${esc(r.produtos?.codigo_barras||'-')}</b><small>${esc(r.produtos?.modelo||'-')}</small></div><div><span class="rpBadge ${r.tipo==='Quebrada'?'q':'a'}">${esc(r.tipo)}</span><small>${esc(r.motivo||'Sem motivo')}</small></div><div><b>${esc(SETORES[Number(r.setor_id)]||'-')}</b><small>${esc(nomePessoa(r.usuario_id))}</small></div><div><span class="rpBadge ${r.status==='Reprocessada'?'r':''}">${esc(r.status||'Aberta')}</span></div><time>${fmt(r.criado_em)}</time>${r.status==='Reprocessada'?'<span></span>':`<button class="rpAction" data-rp-reprocessar="${r.id}">REPROCESSAR</button>`}</div>`).join(''):'<div class="rpEmpty">Nenhuma perda no período.</div>';
 det.querySelectorAll('[data-rp-reprocessar]').forEach(b=>b.onclick=()=>reprocessar(b.dataset.rpReprocessar,periodo));o.querySelector('[data-rp-status]').textContent=`${av.length} ocorrências carregadas • ${iniciadas} peças iniciadas no corte • período: ${periodo==='hoje'?'Hoje':periodo==='7d'?'7 dias':periodo==='30d'?'30 dias':'Mês atual'}`}

async function reprocessar(id,periodo){const o=document.querySelector('.rpOverlay');const st=o?.querySelector('[data-rp-status]');if(st)st.textContent='Marcando peça para reprocessamento...';const{data:{session}}=await supabase.auth.getSession();if(!session){if(st)st.textContent='Sessão expirada.';return}const{error}=await supabase.from('avarias').update({status:'Reprocessada',reprocessado_em:new Date().toISOString(),reprocessado_por:session.user.id}).eq('id',id);if(error){if(st)st.textContent=`Erro: ${error.message}`;return}await carregar(periodo)}

async function abrir(){estilos();document.querySelector('.rpOverlay')?.remove();const o=document.createElement('section');o.className='rpOverlay';o.innerHTML=`<div class="rpShell"><div class="rpTop"><div><small>QUALIDADE E PERDAS</small><h1>Relatório de perdas e retrabalho</h1><p>Quebras, avarias, reprocessamento, setores, modelos e funcionários.</p></div><button class="rpBack" type="button">← Voltar</button></div><div class="rpPanel"><div class="rpQuick"><button data-p="hoje">Hoje</button><button data-p="7d">7 dias</button><button data-p="30d">30 dias</button><button data-p="mes">Mês atual</button></div><div data-rp-status class="rpStatus">Carregando...</div></div><div class="rpCards"><div class="rpCard"><span>Quebradas</span><strong data-rp-quebradas>0</strong></div><div class="rpCard"><span>Avariadas</span><strong data-rp-avariadas>0</strong></div><div class="rpCard"><span>Reprocessadas</span><strong data-rp-reprocessadas>0</strong></div><div class="rpCard"><span>Aproveitamento</span><strong data-rp-aproveit>0</strong></div><div class="rpCard"><span>Taxa de perdas</span><strong data-rp-taxa>0%</strong></div></div><div class="rpGrid"><div class="rpPanel"><h2 class="rpTitle">Perdas por setor</h2><div class="rpSub">Onde as ocorrências aconteceram.</div><div data-rp-setores></div></div><div class="rpPanel"><h2 class="rpTitle">Perdas por modelo</h2><div class="rpSub">Modelos com maior incidência.</div><div data-rp-modelos></div></div></div><div class="rpPanel"><h2 class="rpTitle">Perdas por funcionário</h2><div class="rpSub">Quem registrou cada ocorrência.</div><div data-rp-pessoas></div></div><div class="rpPanel"><h2 class="rpTitle">Histórico e reprocessamento</h2><div class="rpSub">Marque uma ocorrência como reprocessada sem apagar o histórico original.</div><div data-rp-detalhes><div class="rpEmpty">Carregando...</div></div></div></div>`;document.body.appendChild(o);o.querySelector('.rpBack').onclick=()=>o.remove();let atual='hoje';const botoes=[...o.querySelectorAll('[data-p]')];const selecionar=async p=>{atual=p;botoes.forEach(b=>b.classList.toggle('active',b.dataset.p===p));o.querySelector('[data-rp-status]').textContent='Carregando dados...';try{await carregar(p)}catch(e){o.querySelector('[data-rp-status]').textContent=`Não foi possível carregar: ${e.message}`}};botoes.forEach(b=>b.onclick=()=>selecionar(b.dataset.p));selecionar(atual)}

function instalar(){const nav=document.querySelector('.appNav');if(!nav||nav.querySelector('[data-rp-button]'))return;const b=document.createElement('button');b.type='button';b.className='rpNav';b.dataset.rpButton='true';b.innerHTML='<span aria-hidden="true">📉</span> Relatório de perdas';b.onclick=abrir;nav.appendChild(b)}
estilos();instalar();new MutationObserver(instalar).observe(document.body,{childList:true,subtree:true});
